### ISSUE TITLE
Project Task: wide review tracking

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wcag2ict#430]
This is a meta issue to track wide review steps for the note.
See [How to do wide review](https://www.w3.org/Guide/documentreview/#who_to_ask_for_review) for details.

- the groups listed in the WG's charter, especially those who manage dependencies
- the groups jointly responsible for a particular document (if any).
- the horizontal groups:
  - Accessibility
      - [x] [APA Open Issue](https://github.com/w3c/a11y-request/issues/88)
      - [x] #464 - Answer completed, awaiting agreement from submitter
      - [x] #465 - Answer completed, awaiting agreement from submitter
      - [x] #466 - Answer completed, awaiting agreement from submitter
  - Architecture
      - [x] [TAG open issue](https://github.com/w3ctag/design-reviews/issues/973)
  - Internationalization
      - [x] [I18n open issue](https://github.com/w3c/i18n-request/issues/237)
      - [x] #463 - Answer completed, agreed by submitter on 8 Sept. via [issue comment](https://github.com/w3c/wcag2ict/issues/463#issuecomment-2337024735)
  - Privacy
      - [x] [Privacy open issue](https://github.com/w3cping/privacy-request/issues/139)
      - [x] #446 - Answer completed, agreed by submitter on 22 July ([comment in the Google doc](https://docs.google.com/document/d/1YfD_Rxeg72vLZXBuV05BDvlKFCjwy5KZEOeeJSTtfLY/edit?disco=AAABR2DzhFs))
  - Security
      - [x] [Security open issue](https://github.com/w3c/security-request/issues/72)
      - [x] #508
- Other outreach (if applicable)

For more background, see related #335

**Comment by maryjom** [comment]
I have created a [Google doc on horizontal review comments](https://docs.google.com/document/d/1YfD_Rxeg72vLZXBuV05BDvlKFCjwy5KZEOeeJSTtfLY/edit#heading=h.oodjzuanyb6i) where the TF will work on any document changes and issue answers to resolve issues raised in the horizontal review.

**Comment by maryjom** [comment]
All changes due to horizontal review comments have been incorporated into the latest Editor's draft as of 17 Sept.

**Comment by maryjom** [comment]
All PRs to address horizontal review issues have been merged and the issues answered. Closing this issue as complete.
